### ISSUE TITLE
problem in flower classification team4

### ISSUE THREAD

**Issue by mohamedalswaify** [MohmedAAK/-Advanced-computer-vision-v1#9]
@MohmedAAK 
please turn to look at the first cell and help me with the solution

**Comment by MohmedAAK** [comment]
@mohamedgamal1455 
The only way to run kaggle code is by running it on kaggle itself
Solution :
Go to source code that exists on kaggle website that exists in competition notebooks
Then try to save a copy and try to edit it
If you are stuck 
https://youtu.be/lU0XrwtOttk
